files:
  - source: /frontend/i18n/ja.yml
    translation: /frontend/i18n/%two_letters_code%.yml
  - source: /backend/config/locales/ja.yml
    translation: /backend/config/locales/%two_letters_code%.yml
