# frozen_string_literal: true
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]

  gem "rspec", "~> 3.12"
  gem "rspec-rails", "~> 6.0"
  gem "parallel_tests", "~> 4.2"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"
  gem "rubocop", "~> 1.42", require: false
  gem "rubocop-rails", "~> 2.17", require: false
  gem "rubocop-discourse", "~> 3.0", require: false

  gem "webrick", "~> 1.7"
  gem "syntax_tree", "~> 5.1", require: false
end

group :production do
  gem "falcon", "~> 0.42"
end

gem "shortuuid", "~> 0.6.0"

gem "dotenv-rails", "~> 2.8"

gem "openssl-oaep", "~> 0.1.0"

gem "connection_pool", "~> 2.3"

gem "request_store_rails", "~> 2.0"

gem "aws-sdk-s3", "~> 1.117"

gem "bullet", group: "development"

gem "http", "~> 5.1"

gem "pg", "~> 1.4"

gem "nokogiri", "~> 1.14.0.rc1"

gem "color-generator", "~> 0.0.4"

gem "counter_culture", "~> 3.2"

gem "sidekiq", "~> 7.0"
