# frozen_string_literal: true
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0"

# Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 5.3"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]

  gem "rspec", "~> 3.13"
  gem "rspec-rails", "~> 7.1"
end

group :development do
  gem "rubocop", "~> 1.79", require: false
  gem "rubocop-rails", "~> 2.32", require: false

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"

  gem "syntax_tree", "~> 6.2", require: false
end

gem "shortuuid", "~> 0.6.0"

gem "dotenv-rails", "~> 3.1"

gem "openssl-oaep", "~> 0.1.0"

gem "connection_pool", "~> 2.4"

gem "request_store_rails", "~> 2.0"

# https://github.com/rails/rails/issues/54374#issuecomment-2617377315
gem "aws-sdk-core", "3.211"
gem "aws-sdk-s3", "1.170", require: false

gem "bullet", group: "development"

gem "http", "~> 5.2"

gem "pg", "~> 1.5"

gem "nokogiri", "~> 1.18"

gem "color-generator", "~> 0.0.4"

gem "counter_culture", "~> 3.8"

gem "sidekiq", "~> 7.3"

gem "console", "~> 1.29"

gem "sentry-ruby", "~> 5.22"

gem "sentry-rails", "~> 5.22"

gem "sentry-sidekiq", "~> 5.22"

gem "jwt", "~> 2.10"
gem "rbnacl", "~> 7.1"

gem "rails-i18n", "~> 8.0"

gem "net-smtp", "= 0.5.0"

gem "hiredis-client", "~> 0.25.0"

gem "opentelemetry-instrumentation-all", "~> 0.78.0"
gem "opentelemetry-sdk", "~> 1.8"

gem "opentelemetry-exporter-otlp", "~> 0.30.0"

gem "stackprof", "~> 0.2.27"

gem "puma", "~> 6.6"
