# frozen_string_literal: true
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

task lint: :environment do
  sh "rubocop"
end

task format: :environment do
  sh "stree write ./**/*.rb"
  sh "rubocop -a"
end

task "dev:stackprof" do # rubocop:disable Rails/RakeEnvironment
  path = Rails.root.join("tmp/stackprof-dev.txt")
  if path.exist?
    puts "StackProf disabled for development mode."
    path.delete
  else
    puts "StackProf enabled for development mode."
    path.write("")
  end
end
