name: "Build and push docker image"

inputs:
  directory-name:
    description: "Name of the directory"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare meta
      id: meta
      uses: ./.github/actions/meta
      with:
        directory-name: ${{ inputs.directory-name }}

    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-${{ inputs.directory-name }}-*
        merge-multiple: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Create manifest list and push
      shell: bash
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create \
        ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.date }} \
        ${{ steps.meta.outputs.image }}:latest \
        $(printf "${{ steps.meta.outputs.image }}@sha256:%s " *)

    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.date }}
