name: "[sub-audio] Lint, test"

on:
  push:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
      - "Rakefile"
      - "config.test.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Setup .env
        run: |
          cp ./config.test.yml ./config.yml
          rake configure

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version-file: sub-audio/.python-version

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.2

      - name: Config poetry
        run: poetry config virtualenvs.create false

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('./sub-audio/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        working-directory: ./sub-audio
        run: poetry install --with dev,test

      - name: Run sub-audio lint
        working-directory: ./sub-audio
        run: |
          poetry run poe lint

      - name: Run sub-audio test
        working-directory: ./sub-audio
        run: |
          poetry run poe test

      - name: Build image
        if: github.ref_name == 'main'
        uses: ./.github/actions/build
        with:
          directory-name: sub-audio
