name: "[sub-audio] Lint, test"

on:
  push:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
      - ".github/actions/**"
      - "Rakefile"
      - "config.test.yml"
    branches:
      - main
  pull_request:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
      - ".github/actions/**"
      - "Rakefile"
      - "config.test.yml"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
      - name: Setup .env
        run: |
          cp ./config.test.yml ./config.yml
          rake configure

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version-file: sub-audio/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ hashFiles('./sub-audio/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      - name: Setup sub-temp-storage
        run: |
          docker compose -f docker-compose.build.yml up -d sub-temp-storage

      - name: Install dependencies
        working-directory: ./sub-audio
        run: uv sync

      - name: Run sub-audio lint
        working-directory: ./sub-audio
        run: |
          uv run task lint

      - name: Run sub-audio test
        working-directory: ./sub-audio
        run: |
          uv run task test

  build:
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    needs:
      - check
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        uses: ./.github/actions/build
        with:
          directory-name: sub-audio
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge image
        uses: ./.github/actions/merge
        with:
          directory-name: sub-audio
